language: python
python:
  - "2.7"
services:
    - docker
install:
    - docker build . -t freecadtest-i
    - docker run --name freecadtest -v $(pwd)/test:/var/app/test -
        -detach freecadtest-i
script:
    - docker exec -it freecadtest python -m unittest discover test "*_test.py"
